waveformgenerator: waveformgenerator.c waveformgenerator.h
	gcc -o waveformgenerator waveformgenerator.c

test:
	./waveformgenerator ../test/test.wav ../test/test.png

clean:
	rm -f waveformgenerator
